### ISSUE TITLE
Is incompatible with latest version of avalonia

### ISSUE THREAD

**Issue by apache-hb** [amazerol/AvaloniaRibbon#1]
Installing the package through the dotnet CLI with 
`dotnet add package RibbonControl --version 1.0.0-build230619-12`
leads to a package downgrade error
`Detected package downgrade: Avalonia from 0.8.1-cibuild0003059-beta to 0.8.0. Reference the package directly from the project to select a different version.`

**Comment by amazerol** [comment]
Sorry about that, I'll need to update that now.

**Comment by amazerol** [comment]
That works with Avalonia 0.8.2 now.

**Comment by amazerol** [comment]
Maybe I've been too fast in saying that this works ... give me some time

**Comment by amazerol** [comment]
Done ! Version 1.0.2 is compatible with avalonia 0.8.1 and normally upper version !
Enjoy !
