### ISSUE TITLE
Broken Nuget Package?

### ISSUE THREAD

**Issue by nlogozzo** [amazerol/AvaloniaRibbon#12]
I installed the ribbon package with `Install-Package AvaloniaUIRibbon -Version 1.0.5-beta` and it seems to not be working.

First, I see this error triangle in the solution explorer:
![image](https://user-images.githubusercontent.com/17648453/105869186-f6932800-5fc4-11eb-9cde-91f96eadbc88.png)

Second, I included the style with: `<StyleInclude Source="avares://Avalonia.Controls.Ribbon/Styles/RibbonStyles.xaml"/>` and get this error:
![image](https://user-images.githubusercontent.com/17648453/105869306-162a5080-5fc5-11eb-9679-e364d7580f8d.png)

Third, I included the ribbon with `xmlns:ribbon="clr-namespace:AvaloniaUI.Ribbon;assembly=AvaloniaUI.Ribbon"` and my designer doesn't work:
![image](https://user-images.githubusercontent.com/17648453/105869366-293d2080-5fc5-11eb-86b9-04725913c0ac.png)

Is there a different package that i should be using?

**Comment by jinyuttt** [comment]
https://github.com/Splitwirez/AvaloniaRibbon
